/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth.verify-otp'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppMeetingsRouteImport } from './routes/app.meetings'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppPeerReviewRouteImport } from './routes/app.peer-review'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as GuideAiSummaryRouteImport } from './routes/guide.ai-summary'
import { Route as GuideAlertsRouteImport } from './routes/guide.alerts'
import { Route as GuideAnalyticsRouteImport } from './routes/guide.analytics'
import { Route as GuideCalendarRouteImport } from './routes/guide.calendar'
import { Route as GuideDashboardRouteImport } from './routes/guide.dashboard'
import { Route as GuideGroupsRouteImport } from './routes/guide.groups'
import { Route as GuideMessagesRouteImport } from './routes/guide.messages'
import { Route as GuideNotificationsRouteImport } from './routes/guide.notifications'
import { Route as GuideProfileRouteImport } from './routes/guide.profile'
import { Route as GuideReportsRouteImport } from './routes/guide.reports'
import { Route as GuideRiskRadarRouteImport } from './routes/guide.risk-radar'
import { Route as GuideSearchRouteImport } from './routes/guide.search'
import { Route as GuideSettingsRouteImport } from './routes/guide.settings'
import { Route as GuideSubmissionsRouteImport } from './routes/guide.submissions'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as JoinTokenRouteImport } from './routes/join/$token'
import { Route as AppChatUserIdRouteImport } from './routes/app.chat.$userId'
import { Route as AppGroupsIndexRouteImport } from './routes/app.groups.index'
import { Route as AppGroupsGroupIdRouteImport } from './routes/app.groups.$groupId'
import { Route as GuideChatUserIdRouteImport } from './routes/guide.chat.$userId'
import { Route as GuideMembersMemberIdRouteImport } from './routes/guide.members.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPeerReviewRoute = AppPeerReviewRouteImport.update({
  id: '/peer-review',
  path: '/peer-review',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const GuideAiSummaryRoute = GuideAiSummaryRouteImport.update({
  id: '/ai-summary',
  path: '/ai-summary',
  getParentRoute: () => GuideRoute,
} as any)
const GuideAlertsRoute = GuideAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => GuideRoute,
} as any)
const GuideAnalyticsRoute = GuideAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => GuideRoute,
} as any)
const GuideCalendarRoute = GuideCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => GuideRoute,
} as any)
const GuideDashboardRoute = GuideDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GuideRoute,
} as any)
const GuideGroupsRoute = GuideGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => GuideRoute,
} as any)
const GuideMessagesRoute = GuideMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => GuideRoute,
} as any)
const GuideNotificationsRoute = GuideNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => GuideRoute,
} as any)
const GuideProfileRoute = GuideProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => GuideRoute,
} as any)
const GuideReportsRoute = GuideReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => GuideRoute,
} as any)
const GuideRiskRadarRoute = GuideRiskRadarRouteImport.update({
  id: '/risk-radar',
  path: '/risk-radar',
  getParentRoute: () => GuideRoute,
} as any)
const GuideSearchRoute = GuideSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => GuideRoute,
} as any)
const GuideSettingsRoute = GuideSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => GuideRoute,
} as any)
const GuideSubmissionsRoute = GuideSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => GuideRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatUserIdRoute = AppChatUserIdRouteImport.update({
  id: '/chat/$userId',
  path: '/chat/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdRoute = AppGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const GuideChatUserIdRoute = GuideChatUserIdRouteImport.update({
  id: '/chat/$userId',
  path: '/chat/$userId',
  getParentRoute: () => GuideRoute,
} as any)
const GuideMembersMemberIdRoute = GuideMembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => GuideRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/guide': typeof GuideRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/peer-review': typeof AppPeerReviewRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/guide/ai-summary': typeof GuideAiSummaryRoute
  '/guide/alerts': typeof GuideAlertsRoute
  '/guide/analytics': typeof GuideAnalyticsRoute
  '/guide/calendar': typeof GuideCalendarRoute
  '/guide/dashboard': typeof GuideDashboardRoute
  '/guide/groups': typeof GuideGroupsRoute
  '/guide/messages': typeof GuideMessagesRoute
  '/guide/notifications': typeof GuideNotificationsRoute
  '/guide/profile': typeof GuideProfileRoute
  '/guide/reports': typeof GuideReportsRoute
  '/guide/risk-radar': typeof GuideRiskRadarRoute
  '/guide/search': typeof GuideSearchRoute
  '/guide/settings': typeof GuideSettingsRoute
  '/guide/submissions': typeof GuideSubmissionsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/app/chat/$userId': typeof AppChatUserIdRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/guide/chat/$userId': typeof GuideChatUserIdRoute
  '/guide/members/$memberId': typeof GuideMembersMemberIdRoute
  '/app/groups/': typeof AppGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/guide': typeof GuideRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/peer-review': typeof AppPeerReviewRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/guide/ai-summary': typeof GuideAiSummaryRoute
  '/guide/alerts': typeof GuideAlertsRoute
  '/guide/analytics': typeof GuideAnalyticsRoute
  '/guide/calendar': typeof GuideCalendarRoute
  '/guide/dashboard': typeof GuideDashboardRoute
  '/guide/groups': typeof GuideGroupsRoute
  '/guide/messages': typeof GuideMessagesRoute
  '/guide/notifications': typeof GuideNotificationsRoute
  '/guide/profile': typeof GuideProfileRoute
  '/guide/reports': typeof GuideReportsRoute
  '/guide/risk-radar': typeof GuideRiskRadarRoute
  '/guide/search': typeof GuideSearchRoute
  '/guide/settings': typeof GuideSettingsRoute
  '/guide/submissions': typeof GuideSubmissionsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/app/chat/$userId': typeof AppChatUserIdRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/guide/chat/$userId': typeof GuideChatUserIdRoute
  '/guide/members/$memberId': typeof GuideMembersMemberIdRoute
  '/app/groups': typeof AppGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/guide': typeof GuideRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/peer-review': typeof AppPeerReviewRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/guide/ai-summary': typeof GuideAiSummaryRoute
  '/guide/alerts': typeof GuideAlertsRoute
  '/guide/analytics': typeof GuideAnalyticsRoute
  '/guide/calendar': typeof GuideCalendarRoute
  '/guide/dashboard': typeof GuideDashboardRoute
  '/guide/groups': typeof GuideGroupsRoute
  '/guide/messages': typeof GuideMessagesRoute
  '/guide/notifications': typeof GuideNotificationsRoute
  '/guide/profile': typeof GuideProfileRoute
  '/guide/reports': typeof GuideReportsRoute
  '/guide/risk-radar': typeof GuideRiskRadarRoute
  '/guide/search': typeof GuideSearchRoute
  '/guide/settings': typeof GuideSettingsRoute
  '/guide/submissions': typeof GuideSubmissionsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/app/chat/$userId': typeof AppChatUserIdRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/guide/chat/$userId': typeof GuideChatUserIdRoute
  '/guide/members/$memberId': typeof GuideMembersMemberIdRoute
  '/app/groups/': typeof AppGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/guide'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-otp'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/meetings'
    | '/app/messages'
    | '/app/notifications'
    | '/app/peer-review'
    | '/app/performance'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/app/tasks'
    | '/guide/ai-summary'
    | '/guide/alerts'
    | '/guide/analytics'
    | '/guide/calendar'
    | '/guide/dashboard'
    | '/guide/groups'
    | '/guide/messages'
    | '/guide/notifications'
    | '/guide/profile'
    | '/guide/reports'
    | '/guide/risk-radar'
    | '/guide/search'
    | '/guide/settings'
    | '/guide/submissions'
    | '/invite/$token'
    | '/join/$token'
    | '/app/chat/$userId'
    | '/app/groups/$groupId'
    | '/guide/chat/$userId'
    | '/guide/members/$memberId'
    | '/app/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/guide'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-otp'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/meetings'
    | '/app/messages'
    | '/app/notifications'
    | '/app/peer-review'
    | '/app/performance'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/app/tasks'
    | '/guide/ai-summary'
    | '/guide/alerts'
    | '/guide/analytics'
    | '/guide/calendar'
    | '/guide/dashboard'
    | '/guide/groups'
    | '/guide/messages'
    | '/guide/notifications'
    | '/guide/profile'
    | '/guide/reports'
    | '/guide/risk-radar'
    | '/guide/search'
    | '/guide/settings'
    | '/guide/submissions'
    | '/invite/$token'
    | '/join/$token'
    | '/app/chat/$userId'
    | '/app/groups/$groupId'
    | '/guide/chat/$userId'
    | '/guide/members/$memberId'
    | '/app/groups'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/guide'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_auth/verify-otp'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/meetings'
    | '/app/messages'
    | '/app/notifications'
    | '/app/peer-review'
    | '/app/performance'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/app/tasks'
    | '/guide/ai-summary'
    | '/guide/alerts'
    | '/guide/analytics'
    | '/guide/calendar'
    | '/guide/dashboard'
    | '/guide/groups'
    | '/guide/messages'
    | '/guide/notifications'
    | '/guide/profile'
    | '/guide/reports'
    | '/guide/risk-radar'
    | '/guide/search'
    | '/guide/settings'
    | '/guide/submissions'
    | '/invite/$token'
    | '/join/$token'
    | '/app/chat/$userId'
    | '/app/groups/$groupId'
    | '/guide/chat/$userId'
    | '/guide/members/$memberId'
    | '/app/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  GuideRoute: typeof GuideRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings': {
      id: '/app/meetings'
      path: '/meetings'
      fullPath: '/app/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/peer-review': {
      id: '/app/peer-review'
      path: '/peer-review'
      fullPath: '/app/peer-review'
      preLoaderRoute: typeof AppPeerReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/guide/ai-summary': {
      id: '/guide/ai-summary'
      path: '/ai-summary'
      fullPath: '/guide/ai-summary'
      preLoaderRoute: typeof GuideAiSummaryRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/alerts': {
      id: '/guide/alerts'
      path: '/alerts'
      fullPath: '/guide/alerts'
      preLoaderRoute: typeof GuideAlertsRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/analytics': {
      id: '/guide/analytics'
      path: '/analytics'
      fullPath: '/guide/analytics'
      preLoaderRoute: typeof GuideAnalyticsRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/calendar': {
      id: '/guide/calendar'
      path: '/calendar'
      fullPath: '/guide/calendar'
      preLoaderRoute: typeof GuideCalendarRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/dashboard': {
      id: '/guide/dashboard'
      path: '/dashboard'
      fullPath: '/guide/dashboard'
      preLoaderRoute: typeof GuideDashboardRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/groups': {
      id: '/guide/groups'
      path: '/groups'
      fullPath: '/guide/groups'
      preLoaderRoute: typeof GuideGroupsRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/messages': {
      id: '/guide/messages'
      path: '/messages'
      fullPath: '/guide/messages'
      preLoaderRoute: typeof GuideMessagesRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/notifications': {
      id: '/guide/notifications'
      path: '/notifications'
      fullPath: '/guide/notifications'
      preLoaderRoute: typeof GuideNotificationsRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/profile': {
      id: '/guide/profile'
      path: '/profile'
      fullPath: '/guide/profile'
      preLoaderRoute: typeof GuideProfileRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/reports': {
      id: '/guide/reports'
      path: '/reports'
      fullPath: '/guide/reports'
      preLoaderRoute: typeof GuideReportsRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/risk-radar': {
      id: '/guide/risk-radar'
      path: '/risk-radar'
      fullPath: '/guide/risk-radar'
      preLoaderRoute: typeof GuideRiskRadarRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/search': {
      id: '/guide/search'
      path: '/search'
      fullPath: '/guide/search'
      preLoaderRoute: typeof GuideSearchRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/settings': {
      id: '/guide/settings'
      path: '/settings'
      fullPath: '/guide/settings'
      preLoaderRoute: typeof GuideSettingsRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/submissions': {
      id: '/guide/submissions'
      path: '/submissions'
      fullPath: '/guide/submissions'
      preLoaderRoute: typeof GuideSubmissionsRouteImport
      parentRoute: typeof GuideRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/chat/$userId': {
      id: '/app/chat/$userId'
      path: '/chat/$userId'
      fullPath: '/app/chat/$userId'
      preLoaderRoute: typeof AppChatUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/groups/': {
      id: '/app/groups/'
      path: '/groups'
      fullPath: '/app/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/groups/$groupId': {
      id: '/app/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/app/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/guide/chat/$userId': {
      id: '/guide/chat/$userId'
      path: '/chat/$userId'
      fullPath: '/guide/chat/$userId'
      preLoaderRoute: typeof GuideChatUserIdRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/members/$memberId': {
      id: '/guide/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/guide/members/$memberId'
      preLoaderRoute: typeof GuideMembersMemberIdRouteImport
      parentRoute: typeof GuideRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPeerReviewRoute: typeof AppPeerReviewRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppChatUserIdRoute: typeof AppChatUserIdRoute
  AppGroupsGroupIdRoute: typeof AppGroupsGroupIdRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPeerReviewRoute: AppPeerReviewRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppChatUserIdRoute: AppChatUserIdRoute,
  AppGroupsGroupIdRoute: AppGroupsGroupIdRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface GuideRouteChildren {
  GuideAiSummaryRoute: typeof GuideAiSummaryRoute
  GuideAlertsRoute: typeof GuideAlertsRoute
  GuideAnalyticsRoute: typeof GuideAnalyticsRoute
  GuideCalendarRoute: typeof GuideCalendarRoute
  GuideDashboardRoute: typeof GuideDashboardRoute
  GuideGroupsRoute: typeof GuideGroupsRoute
  GuideMessagesRoute: typeof GuideMessagesRoute
  GuideNotificationsRoute: typeof GuideNotificationsRoute
  GuideProfileRoute: typeof GuideProfileRoute
  GuideReportsRoute: typeof GuideReportsRoute
  GuideRiskRadarRoute: typeof GuideRiskRadarRoute
  GuideSearchRoute: typeof GuideSearchRoute
  GuideSettingsRoute: typeof GuideSettingsRoute
  GuideSubmissionsRoute: typeof GuideSubmissionsRoute
  GuideChatUserIdRoute: typeof GuideChatUserIdRoute
  GuideMembersMemberIdRoute: typeof GuideMembersMemberIdRoute
}

const GuideRouteChildren: GuideRouteChildren = {
  GuideAiSummaryRoute: GuideAiSummaryRoute,
  GuideAlertsRoute: GuideAlertsRoute,
  GuideAnalyticsRoute: GuideAnalyticsRoute,
  GuideCalendarRoute: GuideCalendarRoute,
  GuideDashboardRoute: GuideDashboardRoute,
  GuideGroupsRoute: GuideGroupsRoute,
  GuideMessagesRoute: GuideMessagesRoute,
  GuideNotificationsRoute: GuideNotificationsRoute,
  GuideProfileRoute: GuideProfileRoute,
  GuideReportsRoute: GuideReportsRoute,
  GuideRiskRadarRoute: GuideRiskRadarRoute,
  GuideSearchRoute: GuideSearchRoute,
  GuideSettingsRoute: GuideSettingsRoute,
  GuideSubmissionsRoute: GuideSubmissionsRoute,
  GuideChatUserIdRoute: GuideChatUserIdRoute,
  GuideMembersMemberIdRoute: GuideMembersMemberIdRoute,
}

const GuideRouteWithChildren = GuideRoute._addFileChildren(GuideRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  GuideRoute: GuideRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
